spring:
    application:
        name: Google-Oauth2
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        redirect-uri: http://localhost:8080/api/auth/google/callback
        jwt:
            secret_key: jwt-token
            expiration: 604800

server:
    port: 8080
    error:
        include-message: always